### ISSUE TITLE
Error with PyQt5

### ISSUE THREAD

**Issue by bafonso** [timcera/spyder-desktop-ubuntu#1]
Currently the image does not work well and this is what you get if you simply try to start it:

`docker run -it timcera/spyder-desktop-ubuntu /bin/bash
`
```
root@584786a1a1b1:/# spyder3
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libasound.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/spyder3", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/spyder/app/start.py", line 158, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python3.5/dist-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/usr/local/lib/python3.5/dist-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named 'PyQt5.QtWebKitWidgets'

```

**Comment by JohannesWiesner** [comment]
I can confirm this
